### ISSUE TITLE
Message-Editor subject changed event -> terrible performance when lots of folders

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#177]
## Description ##
- Message-editor performance is terribly bad when mailbox has many folders (>50)
- Folders object contain HATEOAS links for actions.
- Each link is (>150 chars long), there are (as of now) 10 links per folder. (50*2*10*150 ~= 100 KB)

## Possible actions ##
- [x] Store state using Web worker -> #178 
- [x] Persistence of state in IndexedDB should be debounced -> #179 
- [x] Complete folders only stored in folders.explodedItems -> #202
- [x] Remove links from folders -> #256

**Comment by shift-reality** [comment]
-"Remove links from folders"
Best way

**Comment by manusa** [comment]
Good performance after all actions have been tackled
